@startuml
user -> CatalogDao: removeBookFromCatalogRequest()

CatalogDao -> Database: markAsInactive(bookId)

Database -> CatalogDao: confirmation message

CatalogDao -> user: Successful deletion message
@enduml
